spring:
  application:
    name: ctbe-open-framework
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/ctbe_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
  cache:
    type: jcache

server:
  port: 8080

# Apache CXF base path for SOAP services
cxf:
  path: /services
